extends:
  - spectral:oas

overrides:
  - files:
      - "docs/openapi.yaml"
    rules:
      # /source/{source_type} (POST) and /source/{connection_id} (GET/PATCH/DELETE)
      # are intentionally different APIs with same path pattern - this is the real API design
      path-params: off
